<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite errors="0" failures="1" hostname="r9000p" name="pytest" skipped="0" tests="11" time="0.102" timestamp="2022-09-20T02:28:30.005759"><testcase classname="tests.test_engine" name="test_BAD" time="0.001"><failure message="KeyError: 'none'">def test_BAD():
&gt;       print(eg["none"])
E       KeyError: 'none'

tests/test_engine.py:42: KeyError</failure></testcase><testcase classname="tests.test_engine" name="test_LIST" time="0.000" /><testcase classname="tests.test_engine" name="test_LS" time="0.000" /><testcase classname="tests.test_engine" name="test_ALL" time="0.017" /><testcase classname="tests.test_engine" name="test_the" time="0.000" /><testcase classname="tests.test_engine" name="test_num" time="0.001" /><testcase classname="tests.test_engine" name="test_sym" time="0.000" /><testcase classname="tests.test_engine" name="test_bignum" time="0.002" /><testcase classname="tests.test_engine" name="test_csv" time="0.002" /><testcase classname="tests.test_engine" name="test_data" time="0.008" /><testcase classname="tests.test_engine" name="test_stats" time="0.007" /></testsuite></testsuites>